{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Avaza API Documentation",
    "description": "Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization[...]"
  },
  "host": "api.avaza.com",
  "schemes": [
    "https"
  ],
  "paths": {
    "/api/Account": {
      "get": {
        "tags": [
          "Account"
        ],
        "summary": "Account Details",
        "operationId": "Account_Get",
        "security": [
          {
            "oauth2": [
              "read_account"
            ]
          }
        ]
      }
    },
    "/api/Company": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Gets list of Companies",
        "operationId": "Company_Get",
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Company"
        ],
        "summary": "Update a Task.",
        "description": "Requires TaskID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.",
        "operationId": "Company_Put",
        "security": [
          {
            "oauth2": [
              "write_contacts"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Company"
        ],
        "summary": "Create a Company",
        "operationId": "Company_Post",
        "security": [
          {
            "oauth2": [
              "write_contacts"
            ]
          }
        ]
      }
    },
    "/api/Company/{id}": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Gets Company by Company ID",
        "operationId": "Company_GetByID",
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ]
      }
    },
    "/api/Contact": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Gets list of Contacts",
        "operationId": "Contact_Get",
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Contact"
        ],
        "summary": "Create a Contact",
        "operationId": "Contact_Post",
        "security": [
          {
            "oauth2": [
              "write_contacts"
            ]
          }
        ]
      }
    },
    "/api/Contact/{id}": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Gets Contact by Contact ID",
        "operationId": "Contact_GetByID",
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ]
      }
    },
    "/api/CreditNote": {
      "get": {
        "tags": [
          "CreditNote"
        ],
        "summary": "Gets list of CreditNotes",
        "operationId": "CreditNote_Get",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/CreditNote/{id}": {
      "get": {
        "tags": [
          "CreditNote"
        ],
        "summary": "Gets Credit Note by CreditNoteID",
        "operationId": "CreditNote_GetByID",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Currency": {
      "get": {
        "tags": [
          "Currency"
        ],
        "summary": "Gets list of Currencies",
        "operationId": "Currency_Get"
      }
    },
    "/api/Estimate": {
      "get": {
        "tags": [
          "Estimate"
        ],
        "summary": "Gets list of Estimates",
        "description": "EstimateStatusCode values are: \"Draft\", \"Sent\", \"Late\", \"Paid\", \"Partial\", \"Void\"",
        "operationId": "Estimate_Get",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Estimate/{id}": {
      "get": {
        "tags": [
          "Estimate"
        ],
        "summary": "Gets Estimate by Estimate ID",
        "operationId": "Estimate_GetByID",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Expense": {
      "get": {
        "tags": [
          "Expense"
        ],
        "summary": "Gets list of Expenses",
        "operationId": "Expense_Get",
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Expense"
        ],
        "summary": "Create an Expense",
        "description": "Create an Expense",
        "operationId": "Expense_Post",
        "security": [
          {
            "oauth2": [
              "write_expenses"
            ]
          }
        ]
      }
    },
    "/api/Expense/{id}": {
      "get": {
        "tags": [
          "Expense"
        ],
        "summary": "Gets an Expense Entry by Expense ID",
        "operationId": "Expense_GetByID",
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ]
      }
    },
    "/api/Inventory": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "Gets list of Inventory",
        "description": "",
        "operationId": "Inventory_Get",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Inventory/{id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "Gets InventoryItem by InventoryItem ID",
        "operationId": "Inventory_GetByID",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Invoice": {
      "get": {
        "tags": [
          "Invoice"
        ],
        "summary": "Gets list of Invoices",
        "description": "TransactionStatusCode values are: \"Draft\", \"Sent\", \"Late\", \"Paid\", \"Partial\", \"Void\"",
        "operationId": "Invoice_Get",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Invoice"
        ],
        "summary": "Create a new draft invoice",
        "operationId": "Invoice_Post",
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ]
      }
    },
    "/api/Invoice/{id}": {
      "get": {
        "tags": [
          "Invoice"
        ],
        "summary": "Gets Invoice by Invoice ID",
        "operationId": "Invoice_GetByID",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Payment": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "Gets list of Payments",
        "operationId": "Payment_Get",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Payment"
        ],
        "summary": "Create new Payment and optionally assign payment allocations to Invoices",
        "operationId": "Payment_Post",
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ]
      }
    },
    "/api/Payment/{id}": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "Gets Payment by Payment Transaction ID",
        "operationId": "Payment_GetByID",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Project": {
      "get": {
        "tags": [
          "Project"
        ],
        "summary": "Gets list of Projects",
        "operationId": "Project_Get",
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Project"
        ],
        "summary": "Create a Project",
        "operationId": "Project_Post",
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ]
      }
    },
    "/api/Project/{id}": {
      "get": {
        "tags": [
          "Project"
        ],
        "summary": "Gets Project by Project ID",
        "operationId": "Project_GetByID",
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ]
      }
    },
    "/api/ProjectTimesheetCategory": {
      "get": {
        "tags": [
          "ProjectTimesheetCategory"
        ],
        "summary": "Gets list of Project Timesheet Categories",
        "operationId": "ProjectTimesheetCategory_Get",
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ]
      }
    },
    "/api/ScheduleAssignment": {
      "get": {
        "tags": [
          "ScheduleAssignment"
        ],
        "summary": "Gets list of Schedule Assignments.",
        "description": "Schedule assignments are per-day, and link to a parent Schedule Series.",
        "operationId": "ScheduleAssignment_Get",
        "security": [
          {
            "oauth2": [
              "read_schedule"
            ]
          }
        ]
      }
    },
    "/api/ScheduleSeries": {
      "get": {
        "tags": [
          "ScheduleSeries"
        ],
        "summary": "Gets list of Schedule Series",
        "description": "Schedule Series represents a strip of time assigned to a user over a date range, for a certain number of hours per day. They can be for Leave or for project work Bookings.",
        "operationId": "ScheduleSeries_Get",
        "security": [
          {
            "oauth2": [
              "read_schedule"
            ]
          }
        ]
      }
    },
    "/api/Section": {
      "get": {
        "tags": [
          "Section"
        ],
        "summary": "Gets list of Sections",
        "operationId": "Section_Get",
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Section"
        ],
        "summary": "Create a Section",
        "operationId": "Section_Post",
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ]
      }
    },
    "/api/Task": {
      "get": {
        "tags": [
          "Task"
        ],
        "summary": "Gets list of Tasks",
        "operationId": "Task_Get",
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Task"
        ],
        "summary": "Update a Task.",
        "description": "Requires TaskID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.",
        "operationId": "Task_Put",
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Task"
        ],
        "summary": "Create a Task",
        "operationId": "Task_Post",
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ]
      }
    },
    "/api/Task/{id}": {
      "get": {
        "tags": [
          "Task"
        ],
        "summary": "Gets Task by Task ID",
        "operationId": "Task_GetByID",
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ]
      }
    },
    "/api/Tax": {
      "get": {
        "tags": [
          "Tax"
        ],
        "summary": "Get List of Taxes configured in the Avaza account.",
        "operationId": "Tax_Get",
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ]
      }
    },
    "/api/Timesheet": {
      "get": {
        "tags": [
          "Timesheet"
        ],
        "summary": "Gets list of Timsheets",
        "operationId": "Timesheet_Get",
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Timesheet"
        ],
        "summary": "Update a Timesheet",
        "description": "The FieldsToUpdate field expects a string array collection of the field names you would like updated.",
        "operationId": "Timesheet_Put",
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Timesheet"
        ],
        "summary": "Create a new Timesheet Entry",
        "operationId": "Timesheet_Post",
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ]
      }
    },
    "/api/Timesheet/{id}": {
      "get": {
        "tags": [
          "Timesheet"
        ],
        "summary": "Gets a Timesheet Entry by Timesheet ID",
        "operationId": "Timesheet_GetByID",
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Timesheet"
        ],
        "summary": "Delete a Timesheet Entry",
        "operationId": "Timesheet_Delete",
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ]
      }
    },
    "/api/TimesheetSubmission": {
      "post": {
        "tags": [
          "TimesheetSubmission"
        ],
        "summary": "Submit Timesheets for Approval.",
        "description": "Either provide a a specific Day (WholeDayOf) or any day in a Week (WholeWeekOf) to submit all draft timesheets in that day or week",
        "operationId": "TimesheetSubmission_Post",
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ]
      }
    },
    "/api/TimesheetTimer": {
      "get": {
        "tags": [
          "TimesheetTimer"
        ],
        "summary": "Gets the  Running Timer if there is one for a user.",
        "operationId": "TimesheetTimer_GetRunningTimer",
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ]
      }
    },
    "/api/TimesheetTimer/{id}": {
      "post": {
        "tags": [
          "TimesheetTimer"
        ],
        "summary": "Starts a Timer running on an existing Timesheet Entry",
        "operationId": "TimesheetTimer_StartTimer",
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "TimesheetTimer"
        ],
        "summary": "Stop the timer running on an existing Timesheet Entry",
        "operationId": "TimesheetTimer_StopTimer",
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ]
      }
    },
    "/api/UserProfile": {
      "get": {
        "tags": [
          "UserProfile"
        ],
        "summary": "Get Collection of Users who have roles in the current Avaza account.",
        "description": "Admin and Invoice Managers can see all. Other users are limited to seeing their own profile.",
        "operationId": "UserProfile_Get",
        "security": [
          {
            "oauth2": [
              "read_users"
            ]
          }
        ]
      }
    },
    "/api/Webhook": {
      "get": {
        "tags": [
          "Webhook"
        ],
        "summary": "Get list of Webhook Subscriptions",
        "operationId": "Webhook_Get",
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webhook"
        ],
        "summary": "Subscribe to Webhook. On success, returns ID of webhook subscription.",
        "description": "When you receive a webhook, you should respond with Http 200 OK Status Code, otherwise we will retry. To create a webhook, you need both the webhook_notifications scope, as well as the scope for the required entity being monitored.  Event values are: \"company_created\", \"company_deleted\", \"company_updated\", \"contact_created\", \"contact_deleted\", \"contact_updated\", \"invoice_created\", \"invoice_sent\", \"project_created\", \"project_deleted\", \"project_updated\[...]",
        "operationId": "Webhook_Post",
        "security": [
          {
            "oauth2": [
              "webhook_notifications",
              "read_contacts",
              "read_account",
              "read_users",
              "read_financials",
              "read_projects",
              "read_schedule",
              "read_timesheets",
              "read_expenses",
              "write_contacts",
              "write_account",
              "write_users",
              "write_financials",
              "write_projects",
              "write_schedule",
              "write_timesheets",
              "write_expenses"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webhook"
        ],
        "summary": "Delete webhook subscription by URL",
        "operationId": "Webhook_DeleteByUrl",
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ]
      }
    },
    "/api/Webhook/{id}": {
      "delete": {
        "tags": [
          "Webhook"
        ],
        "summary": "Delete Webhook Subscription by ID",
        "operationId": "Webhook_Delete",
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "description": "OAuth2 Implicit Grant",
      "flow": "implicit",
      "authorizationUrl": "https://any.avaza.com/oauth2/authorize",
      "scopes": {
        "read_contacts": "Read access to Customers, Contacts",
        "read_account": "Read access to Account metadata",
        "read_users": "Read access to User Profiles",
        "read_financials": "Read access to Estimates, Invoices, Payments, Credit Notes",
        "read_projects": "Read access to Projects, Project Settings, Tasks",
        "read_schedule": "Read access to Schedule Details",
        "read_timesheets": "Read access to Timesheet Details",
        "read_expenses": "Read access to Expense Details",
        "write_contacts": "Write access to Customers, Contacts",
        "write_account": "Write access to Account metadata",
        "write_users": "Write access to User Profiles",
        "write_financials": "Write access to Estimates, Invoices, Payments, Credit Notes",
        "write_projects": "Write access to Projects, Project Settings, Tasks",
        "write_schedule": "Write access to Schedule module",
        "write_timesheets": "Write access to Timesheets module",
        "write_expenses": "Write access to Expense module",
        "webhook_notifications": "Read access to webhook notification events"
      }
    }
  }
}
