# coding: utf-8

"""
    Avaza API Documentation

    Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization endpoint: https://any.avaza.com/oauth2/authorize  <br/>OAuth2 Token endpoint: https://any.avaza.com/oauth2/token<br/>Base URL for subsequent API Requests: https://api.avaza.com/ <br/><br/>Blogpost about authenticating with Avaza's API:  https://www.avaza.com/avaza-api-oauth2-authentication/ <br/>Blogpost on using Avaza's webhooks: https://www.avaza.com/avaza-api-webhook-notifications/<br/>The OAuth flow currently issues Access Tokens that last 1 day, and Refresh tokens that last 180 days<br/>The Api respects the security Roles assigned to the authenticating Avaza user and filters the data return appropriately. <br/><br><strong>Support</strong><br/>For API Support, and to request access please contact Avaza Support Team via our support chat. <br/><br/><strong>User Contributed Libraries:</strong><br/>Graciously contributed by 3rd party users like you. <br/>Note these are not tested or endorsesd by Avaza. We encourage you to review before use, and use at own risk.<br/> <ul><li> - <a target='blank' href='https://packagist.org/packages/debiprasad/oauth2-avaza'>PHP OAuth Client Package for Azava API (by Debiprasad Sahoo)</a></li></ul>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from avazacli.models.company_contact import CompanyContact  # noqa: F401,E501


class Company(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_id': 'int',
        'company_name': 'str',
        'billing_address_line': 'str',
        'billing_address_city': 'str',
        'billing_address_state': 'str',
        'billing_address_post_code': 'str',
        'billing_country_code': 'str',
        'billing_address': 'str',
        'phone': 'str',
        'fax': 'str',
        'website': 'str',
        'tax_number': 'str',
        'comments': 'str',
        'currency_code': 'str',
        'default_trading_term_idfk': 'int',
        'date_created': 'datetime',
        'date_updated': 'datetime',
        'contacts': 'list[CompanyContact]'
    }

    attribute_map = {
        'company_id': 'CompanyID',
        'company_name': 'CompanyName',
        'billing_address_line': 'BillingAddressLine',
        'billing_address_city': 'BillingAddressCity',
        'billing_address_state': 'BillingAddressState',
        'billing_address_post_code': 'BillingAddressPostCode',
        'billing_country_code': 'BillingCountryCode',
        'billing_address': 'BillingAddress',
        'phone': 'Phone',
        'fax': 'Fax',
        'website': 'website',
        'tax_number': 'TaxNumber',
        'comments': 'Comments',
        'currency_code': 'CurrencyCode',
        'default_trading_term_idfk': 'DefaultTradingTermIDFK',
        'date_created': 'DateCreated',
        'date_updated': 'DateUpdated',
        'contacts': 'Contacts'
    }

    def __init__(self, company_id=None, company_name=None, billing_address_line=None, billing_address_city=None, billing_address_state=None, billing_address_post_code=None, billing_country_code=None, billing_address=None, phone=None, fax=None, website=None, tax_number=None, comments=None, currency_code=None, default_trading_term_idfk=None, date_created=None, date_updated=None, contacts=None):  # noqa: E501
        """Company - a model defined in Swagger"""  # noqa: E501

        self._company_id = None
        self._company_name = None
        self._billing_address_line = None
        self._billing_address_city = None
        self._billing_address_state = None
        self._billing_address_post_code = None
        self._billing_country_code = None
        self._billing_address = None
        self._phone = None
        self._fax = None
        self._website = None
        self._tax_number = None
        self._comments = None
        self._currency_code = None
        self._default_trading_term_idfk = None
        self._date_created = None
        self._date_updated = None
        self._contacts = None
        self.discriminator = None

        if company_id is not None:
            self.company_id = company_id
        if company_name is not None:
            self.company_name = company_name
        if billing_address_line is not None:
            self.billing_address_line = billing_address_line
        if billing_address_city is not None:
            self.billing_address_city = billing_address_city
        if billing_address_state is not None:
            self.billing_address_state = billing_address_state
        if billing_address_post_code is not None:
            self.billing_address_post_code = billing_address_post_code
        if billing_country_code is not None:
            self.billing_country_code = billing_country_code
        if billing_address is not None:
            self.billing_address = billing_address
        if phone is not None:
            self.phone = phone
        if fax is not None:
            self.fax = fax
        if website is not None:
            self.website = website
        if tax_number is not None:
            self.tax_number = tax_number
        if comments is not None:
            self.comments = comments
        if currency_code is not None:
            self.currency_code = currency_code
        if default_trading_term_idfk is not None:
            self.default_trading_term_idfk = default_trading_term_idfk
        if date_created is not None:
            self.date_created = date_created
        if date_updated is not None:
            self.date_updated = date_updated
        if contacts is not None:
            self.contacts = contacts

    @property
    def company_id(self):
        """Gets the company_id of this Company.  # noqa: E501


        :return: The company_id of this Company.  # noqa: E501
        :rtype: int
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this Company.


        :param company_id: The company_id of this Company.  # noqa: E501
        :type: int
        """

        self._company_id = company_id

    @property
    def company_name(self):
        """Gets the company_name of this Company.  # noqa: E501


        :return: The company_name of this Company.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this Company.


        :param company_name: The company_name of this Company.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def billing_address_line(self):
        """Gets the billing_address_line of this Company.  # noqa: E501


        :return: The billing_address_line of this Company.  # noqa: E501
        :rtype: str
        """
        return self._billing_address_line

    @billing_address_line.setter
    def billing_address_line(self, billing_address_line):
        """Sets the billing_address_line of this Company.


        :param billing_address_line: The billing_address_line of this Company.  # noqa: E501
        :type: str
        """

        self._billing_address_line = billing_address_line

    @property
    def billing_address_city(self):
        """Gets the billing_address_city of this Company.  # noqa: E501


        :return: The billing_address_city of this Company.  # noqa: E501
        :rtype: str
        """
        return self._billing_address_city

    @billing_address_city.setter
    def billing_address_city(self, billing_address_city):
        """Sets the billing_address_city of this Company.


        :param billing_address_city: The billing_address_city of this Company.  # noqa: E501
        :type: str
        """

        self._billing_address_city = billing_address_city

    @property
    def billing_address_state(self):
        """Gets the billing_address_state of this Company.  # noqa: E501


        :return: The billing_address_state of this Company.  # noqa: E501
        :rtype: str
        """
        return self._billing_address_state

    @billing_address_state.setter
    def billing_address_state(self, billing_address_state):
        """Sets the billing_address_state of this Company.


        :param billing_address_state: The billing_address_state of this Company.  # noqa: E501
        :type: str
        """

        self._billing_address_state = billing_address_state

    @property
    def billing_address_post_code(self):
        """Gets the billing_address_post_code of this Company.  # noqa: E501


        :return: The billing_address_post_code of this Company.  # noqa: E501
        :rtype: str
        """
        return self._billing_address_post_code

    @billing_address_post_code.setter
    def billing_address_post_code(self, billing_address_post_code):
        """Sets the billing_address_post_code of this Company.


        :param billing_address_post_code: The billing_address_post_code of this Company.  # noqa: E501
        :type: str
        """

        self._billing_address_post_code = billing_address_post_code

    @property
    def billing_country_code(self):
        """Gets the billing_country_code of this Company.  # noqa: E501


        :return: The billing_country_code of this Company.  # noqa: E501
        :rtype: str
        """
        return self._billing_country_code

    @billing_country_code.setter
    def billing_country_code(self, billing_country_code):
        """Sets the billing_country_code of this Company.


        :param billing_country_code: The billing_country_code of this Company.  # noqa: E501
        :type: str
        """

        self._billing_country_code = billing_country_code

    @property
    def billing_address(self):
        """Gets the billing_address of this Company.  # noqa: E501


        :return: The billing_address of this Company.  # noqa: E501
        :rtype: str
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address):
        """Sets the billing_address of this Company.


        :param billing_address: The billing_address of this Company.  # noqa: E501
        :type: str
        """

        self._billing_address = billing_address

    @property
    def phone(self):
        """Gets the phone of this Company.  # noqa: E501


        :return: The phone of this Company.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this Company.


        :param phone: The phone of this Company.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def fax(self):
        """Gets the fax of this Company.  # noqa: E501


        :return: The fax of this Company.  # noqa: E501
        :rtype: str
        """
        return self._fax

    @fax.setter
    def fax(self, fax):
        """Sets the fax of this Company.


        :param fax: The fax of this Company.  # noqa: E501
        :type: str
        """

        self._fax = fax

    @property
    def website(self):
        """Gets the website of this Company.  # noqa: E501


        :return: The website of this Company.  # noqa: E501
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this Company.


        :param website: The website of this Company.  # noqa: E501
        :type: str
        """

        self._website = website

    @property
    def tax_number(self):
        """Gets the tax_number of this Company.  # noqa: E501


        :return: The tax_number of this Company.  # noqa: E501
        :rtype: str
        """
        return self._tax_number

    @tax_number.setter
    def tax_number(self, tax_number):
        """Sets the tax_number of this Company.


        :param tax_number: The tax_number of this Company.  # noqa: E501
        :type: str
        """

        self._tax_number = tax_number

    @property
    def comments(self):
        """Gets the comments of this Company.  # noqa: E501


        :return: The comments of this Company.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this Company.


        :param comments: The comments of this Company.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def currency_code(self):
        """Gets the currency_code of this Company.  # noqa: E501


        :return: The currency_code of this Company.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this Company.


        :param currency_code: The currency_code of this Company.  # noqa: E501
        :type: str
        """

        self._currency_code = currency_code

    @property
    def default_trading_term_idfk(self):
        """Gets the default_trading_term_idfk of this Company.  # noqa: E501


        :return: The default_trading_term_idfk of this Company.  # noqa: E501
        :rtype: int
        """
        return self._default_trading_term_idfk

    @default_trading_term_idfk.setter
    def default_trading_term_idfk(self, default_trading_term_idfk):
        """Sets the default_trading_term_idfk of this Company.


        :param default_trading_term_idfk: The default_trading_term_idfk of this Company.  # noqa: E501
        :type: int
        """

        self._default_trading_term_idfk = default_trading_term_idfk

    @property
    def date_created(self):
        """Gets the date_created of this Company.  # noqa: E501


        :return: The date_created of this Company.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this Company.


        :param date_created: The date_created of this Company.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_updated(self):
        """Gets the date_updated of this Company.  # noqa: E501


        :return: The date_updated of this Company.  # noqa: E501
        :rtype: datetime
        """
        return self._date_updated

    @date_updated.setter
    def date_updated(self, date_updated):
        """Sets the date_updated of this Company.


        :param date_updated: The date_updated of this Company.  # noqa: E501
        :type: datetime
        """

        self._date_updated = date_updated

    @property
    def contacts(self):
        """Gets the contacts of this Company.  # noqa: E501


        :return: The contacts of this Company.  # noqa: E501
        :rtype: list[CompanyContact]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this Company.


        :param contacts: The contacts of this Company.  # noqa: E501
        :type: list[CompanyContact]
        """

        self._contacts = contacts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Company):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
