# coding: utf-8

"""
    Avaza API Documentation

    Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization endpoint: https://any.avaza.com/oauth2/authorize  <br/>OAuth2 Token endpoint: https://any.avaza.com/oauth2/token<br/>Base URL for subsequent API Requests: https://api.avaza.com/ <br/><br/>Blogpost about authenticating with Avaza's API:  https://www.avaza.com/avaza-api-oauth2-authentication/ <br/>Blogpost on using Avaza's webhooks: https://www.avaza.com/avaza-api-webhook-notifications/<br/>The OAuth flow currently issues Access Tokens that last 1 day, and Refresh tokens that last 180 days<br/>The Api respects the security Roles assigned to the authenticating Avaza user and filters the data return appropriately. <br/><br><strong>Support</strong><br/>For API Support, and to request access please contact Avaza Support Team via our support chat. <br/><br/><strong>User Contributed Libraries:</strong><br/>Graciously contributed by 3rd party users like you. <br/>Note these are not tested or endorsesd by Avaza. We encourage you to review before use, and use at own risk.<br/> <ul><li> - <a target='blank' href='https://packagist.org/packages/debiprasad/oauth2-avaza'>PHP OAuth Client Package for Azava API (by Debiprasad Sahoo)</a></li></ul>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InvoiceLineItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaction_line_item_id': 'int',
        'inventory_item_idfk': 'int',
        'inventory_item_name': 'str',
        'inventory_item_sku': 'str',
        'description': 'str',
        'quantity': 'float',
        'unit_price': 'float',
        'tax_amount': 'float',
        'tax_idfk': 'int',
        'tax_code': 'str',
        'tax_name': 'str',
        'project_idfk': 'int',
        'project_title': 'str',
        'amount': 'float',
        'discount': 'float'
    }

    attribute_map = {
        'transaction_line_item_id': 'TransactionLineItemID',
        'inventory_item_idfk': 'InventoryItemIDFK',
        'inventory_item_name': 'InventoryItemName',
        'inventory_item_sku': 'InventoryItemSKU',
        'description': 'Description',
        'quantity': 'Quantity',
        'unit_price': 'UnitPrice',
        'tax_amount': 'TaxAmount',
        'tax_idfk': 'TaxIDFK',
        'tax_code': 'TaxCode',
        'tax_name': 'TaxName',
        'project_idfk': 'ProjectIDFK',
        'project_title': 'ProjectTitle',
        'amount': 'Amount',
        'discount': 'Discount'
    }

    def __init__(self, transaction_line_item_id=None, inventory_item_idfk=None, inventory_item_name=None, inventory_item_sku=None, description=None, quantity=None, unit_price=None, tax_amount=None, tax_idfk=None, tax_code=None, tax_name=None, project_idfk=None, project_title=None, amount=None, discount=None):  # noqa: E501
        """InvoiceLineItem - a model defined in Swagger"""  # noqa: E501

        self._transaction_line_item_id = None
        self._inventory_item_idfk = None
        self._inventory_item_name = None
        self._inventory_item_sku = None
        self._description = None
        self._quantity = None
        self._unit_price = None
        self._tax_amount = None
        self._tax_idfk = None
        self._tax_code = None
        self._tax_name = None
        self._project_idfk = None
        self._project_title = None
        self._amount = None
        self._discount = None
        self.discriminator = None

        if transaction_line_item_id is not None:
            self.transaction_line_item_id = transaction_line_item_id
        if inventory_item_idfk is not None:
            self.inventory_item_idfk = inventory_item_idfk
        if inventory_item_name is not None:
            self.inventory_item_name = inventory_item_name
        if inventory_item_sku is not None:
            self.inventory_item_sku = inventory_item_sku
        if description is not None:
            self.description = description
        if quantity is not None:
            self.quantity = quantity
        if unit_price is not None:
            self.unit_price = unit_price
        if tax_amount is not None:
            self.tax_amount = tax_amount
        if tax_idfk is not None:
            self.tax_idfk = tax_idfk
        if tax_code is not None:
            self.tax_code = tax_code
        if tax_name is not None:
            self.tax_name = tax_name
        if project_idfk is not None:
            self.project_idfk = project_idfk
        if project_title is not None:
            self.project_title = project_title
        if amount is not None:
            self.amount = amount
        if discount is not None:
            self.discount = discount

    @property
    def transaction_line_item_id(self):
        """Gets the transaction_line_item_id of this InvoiceLineItem.  # noqa: E501


        :return: The transaction_line_item_id of this InvoiceLineItem.  # noqa: E501
        :rtype: int
        """
        return self._transaction_line_item_id

    @transaction_line_item_id.setter
    def transaction_line_item_id(self, transaction_line_item_id):
        """Sets the transaction_line_item_id of this InvoiceLineItem.


        :param transaction_line_item_id: The transaction_line_item_id of this InvoiceLineItem.  # noqa: E501
        :type: int
        """

        self._transaction_line_item_id = transaction_line_item_id

    @property
    def inventory_item_idfk(self):
        """Gets the inventory_item_idfk of this InvoiceLineItem.  # noqa: E501


        :return: The inventory_item_idfk of this InvoiceLineItem.  # noqa: E501
        :rtype: int
        """
        return self._inventory_item_idfk

    @inventory_item_idfk.setter
    def inventory_item_idfk(self, inventory_item_idfk):
        """Sets the inventory_item_idfk of this InvoiceLineItem.


        :param inventory_item_idfk: The inventory_item_idfk of this InvoiceLineItem.  # noqa: E501
        :type: int
        """

        self._inventory_item_idfk = inventory_item_idfk

    @property
    def inventory_item_name(self):
        """Gets the inventory_item_name of this InvoiceLineItem.  # noqa: E501


        :return: The inventory_item_name of this InvoiceLineItem.  # noqa: E501
        :rtype: str
        """
        return self._inventory_item_name

    @inventory_item_name.setter
    def inventory_item_name(self, inventory_item_name):
        """Sets the inventory_item_name of this InvoiceLineItem.


        :param inventory_item_name: The inventory_item_name of this InvoiceLineItem.  # noqa: E501
        :type: str
        """

        self._inventory_item_name = inventory_item_name

    @property
    def inventory_item_sku(self):
        """Gets the inventory_item_sku of this InvoiceLineItem.  # noqa: E501


        :return: The inventory_item_sku of this InvoiceLineItem.  # noqa: E501
        :rtype: str
        """
        return self._inventory_item_sku

    @inventory_item_sku.setter
    def inventory_item_sku(self, inventory_item_sku):
        """Sets the inventory_item_sku of this InvoiceLineItem.


        :param inventory_item_sku: The inventory_item_sku of this InvoiceLineItem.  # noqa: E501
        :type: str
        """

        self._inventory_item_sku = inventory_item_sku

    @property
    def description(self):
        """Gets the description of this InvoiceLineItem.  # noqa: E501


        :return: The description of this InvoiceLineItem.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InvoiceLineItem.


        :param description: The description of this InvoiceLineItem.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def quantity(self):
        """Gets the quantity of this InvoiceLineItem.  # noqa: E501


        :return: The quantity of this InvoiceLineItem.  # noqa: E501
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this InvoiceLineItem.


        :param quantity: The quantity of this InvoiceLineItem.  # noqa: E501
        :type: float
        """

        self._quantity = quantity

    @property
    def unit_price(self):
        """Gets the unit_price of this InvoiceLineItem.  # noqa: E501


        :return: The unit_price of this InvoiceLineItem.  # noqa: E501
        :rtype: float
        """
        return self._unit_price

    @unit_price.setter
    def unit_price(self, unit_price):
        """Sets the unit_price of this InvoiceLineItem.


        :param unit_price: The unit_price of this InvoiceLineItem.  # noqa: E501
        :type: float
        """

        self._unit_price = unit_price

    @property
    def tax_amount(self):
        """Gets the tax_amount of this InvoiceLineItem.  # noqa: E501


        :return: The tax_amount of this InvoiceLineItem.  # noqa: E501
        :rtype: float
        """
        return self._tax_amount

    @tax_amount.setter
    def tax_amount(self, tax_amount):
        """Sets the tax_amount of this InvoiceLineItem.


        :param tax_amount: The tax_amount of this InvoiceLineItem.  # noqa: E501
        :type: float
        """

        self._tax_amount = tax_amount

    @property
    def tax_idfk(self):
        """Gets the tax_idfk of this InvoiceLineItem.  # noqa: E501


        :return: The tax_idfk of this InvoiceLineItem.  # noqa: E501
        :rtype: int
        """
        return self._tax_idfk

    @tax_idfk.setter
    def tax_idfk(self, tax_idfk):
        """Sets the tax_idfk of this InvoiceLineItem.


        :param tax_idfk: The tax_idfk of this InvoiceLineItem.  # noqa: E501
        :type: int
        """

        self._tax_idfk = tax_idfk

    @property
    def tax_code(self):
        """Gets the tax_code of this InvoiceLineItem.  # noqa: E501


        :return: The tax_code of this InvoiceLineItem.  # noqa: E501
        :rtype: str
        """
        return self._tax_code

    @tax_code.setter
    def tax_code(self, tax_code):
        """Sets the tax_code of this InvoiceLineItem.


        :param tax_code: The tax_code of this InvoiceLineItem.  # noqa: E501
        :type: str
        """

        self._tax_code = tax_code

    @property
    def tax_name(self):
        """Gets the tax_name of this InvoiceLineItem.  # noqa: E501


        :return: The tax_name of this InvoiceLineItem.  # noqa: E501
        :rtype: str
        """
        return self._tax_name

    @tax_name.setter
    def tax_name(self, tax_name):
        """Sets the tax_name of this InvoiceLineItem.


        :param tax_name: The tax_name of this InvoiceLineItem.  # noqa: E501
        :type: str
        """

        self._tax_name = tax_name

    @property
    def project_idfk(self):
        """Gets the project_idfk of this InvoiceLineItem.  # noqa: E501


        :return: The project_idfk of this InvoiceLineItem.  # noqa: E501
        :rtype: int
        """
        return self._project_idfk

    @project_idfk.setter
    def project_idfk(self, project_idfk):
        """Sets the project_idfk of this InvoiceLineItem.


        :param project_idfk: The project_idfk of this InvoiceLineItem.  # noqa: E501
        :type: int
        """

        self._project_idfk = project_idfk

    @property
    def project_title(self):
        """Gets the project_title of this InvoiceLineItem.  # noqa: E501


        :return: The project_title of this InvoiceLineItem.  # noqa: E501
        :rtype: str
        """
        return self._project_title

    @project_title.setter
    def project_title(self, project_title):
        """Sets the project_title of this InvoiceLineItem.


        :param project_title: The project_title of this InvoiceLineItem.  # noqa: E501
        :type: str
        """

        self._project_title = project_title

    @property
    def amount(self):
        """Gets the amount of this InvoiceLineItem.  # noqa: E501


        :return: The amount of this InvoiceLineItem.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InvoiceLineItem.


        :param amount: The amount of this InvoiceLineItem.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def discount(self):
        """Gets the discount of this InvoiceLineItem.  # noqa: E501


        :return: The discount of this InvoiceLineItem.  # noqa: E501
        :rtype: float
        """
        return self._discount

    @discount.setter
    def discount(self, discount):
        """Sets the discount of this InvoiceLineItem.


        :param discount: The discount of this InvoiceLineItem.  # noqa: E501
        :type: float
        """

        self._discount = discount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoiceLineItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
