# coding: utf-8

"""
    Avaza API Documentation

    Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization endpoint: https://any.avaza.com/oauth2/authorize  <br/>OAuth2 Token endpoint: https://any.avaza.com/oauth2/token<br/>Base URL for subsequent API Requests: https://api.avaza.com/ <br/><br/>Blogpost about authenticating with Avaza's API:  https://www.avaza.com/avaza-api-oauth2-authentication/ <br/>Blogpost on using Avaza's webhooks: https://www.avaza.com/avaza-api-webhook-notifications/<br/>The OAuth flow currently issues Access Tokens that last 1 day, and Refresh tokens that last 180 days<br/>The Api respects the security Roles assigned to the authenticating Avaza user and filters the data return appropriately. <br/><br><strong>Support</strong><br/>For API Support, and to request access please contact Avaza Support Team via our support chat. <br/><br/><strong>User Contributed Libraries:</strong><br/>Graciously contributed by 3rd party users like you. <br/>Note these are not tested or endorsesd by Avaza. We encourage you to review before use, and use at own risk.<br/> <ul><li> - <a target='blank' href='https://packagist.org/packages/debiprasad/oauth2-avaza'>PHP OAuth Client Package for Azava API (by Debiprasad Sahoo)</a></li></ul>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from avazacli.models.new_tag import NewTag  # noqa: F401,E501


class NewTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_idfk': 'int',
        'section_idfk': 'int',
        'title': 'str',
        'description': 'str',
        'assigned_to_user_idfk': 'int',
        'date_start': 'datetime',
        'date_start_utc': 'datetime',
        'date_due': 'datetime',
        'date_due_utc': 'datetime',
        'estimated_effort': 'float',
        'tags': 'list[NewTag]'
    }

    attribute_map = {
        'project_idfk': 'ProjectIDFK',
        'section_idfk': 'SectionIDFK',
        'title': 'Title',
        'description': 'Description',
        'assigned_to_user_idfk': 'AssignedToUserIDFK',
        'date_start': 'DateStart',
        'date_start_utc': 'DateStartUTC',
        'date_due': 'DateDue',
        'date_due_utc': 'DateDueUTC',
        'estimated_effort': 'EstimatedEffort',
        'tags': 'Tags'
    }

    def __init__(self, project_idfk=None, section_idfk=None, title=None, description=None, assigned_to_user_idfk=None, date_start=None, date_start_utc=None, date_due=None, date_due_utc=None, estimated_effort=None, tags=None):  # noqa: E501
        """NewTask - a model defined in Swagger"""  # noqa: E501

        self._project_idfk = None
        self._section_idfk = None
        self._title = None
        self._description = None
        self._assigned_to_user_idfk = None
        self._date_start = None
        self._date_start_utc = None
        self._date_due = None
        self._date_due_utc = None
        self._estimated_effort = None
        self._tags = None
        self.discriminator = None

        self.project_idfk = project_idfk
        self.section_idfk = section_idfk
        self.title = title
        if description is not None:
            self.description = description
        if assigned_to_user_idfk is not None:
            self.assigned_to_user_idfk = assigned_to_user_idfk
        if date_start is not None:
            self.date_start = date_start
        if date_start_utc is not None:
            self.date_start_utc = date_start_utc
        if date_due is not None:
            self.date_due = date_due
        if date_due_utc is not None:
            self.date_due_utc = date_due_utc
        if estimated_effort is not None:
            self.estimated_effort = estimated_effort
        if tags is not None:
            self.tags = tags

    @property
    def project_idfk(self):
        """Gets the project_idfk of this NewTask.  # noqa: E501


        :return: The project_idfk of this NewTask.  # noqa: E501
        :rtype: int
        """
        return self._project_idfk

    @project_idfk.setter
    def project_idfk(self, project_idfk):
        """Sets the project_idfk of this NewTask.


        :param project_idfk: The project_idfk of this NewTask.  # noqa: E501
        :type: int
        """
        if project_idfk is None:
            raise ValueError("Invalid value for `project_idfk`, must not be `None`")  # noqa: E501

        self._project_idfk = project_idfk

    @property
    def section_idfk(self):
        """Gets the section_idfk of this NewTask.  # noqa: E501


        :return: The section_idfk of this NewTask.  # noqa: E501
        :rtype: int
        """
        return self._section_idfk

    @section_idfk.setter
    def section_idfk(self, section_idfk):
        """Sets the section_idfk of this NewTask.


        :param section_idfk: The section_idfk of this NewTask.  # noqa: E501
        :type: int
        """
        if section_idfk is None:
            raise ValueError("Invalid value for `section_idfk`, must not be `None`")  # noqa: E501

        self._section_idfk = section_idfk

    @property
    def title(self):
        """Gets the title of this NewTask.  # noqa: E501


        :return: The title of this NewTask.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this NewTask.


        :param title: The title of this NewTask.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this NewTask.  # noqa: E501


        :return: The description of this NewTask.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NewTask.


        :param description: The description of this NewTask.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def assigned_to_user_idfk(self):
        """Gets the assigned_to_user_idfk of this NewTask.  # noqa: E501


        :return: The assigned_to_user_idfk of this NewTask.  # noqa: E501
        :rtype: int
        """
        return self._assigned_to_user_idfk

    @assigned_to_user_idfk.setter
    def assigned_to_user_idfk(self, assigned_to_user_idfk):
        """Sets the assigned_to_user_idfk of this NewTask.


        :param assigned_to_user_idfk: The assigned_to_user_idfk of this NewTask.  # noqa: E501
        :type: int
        """

        self._assigned_to_user_idfk = assigned_to_user_idfk

    @property
    def date_start(self):
        """Gets the date_start of this NewTask.  # noqa: E501


        :return: The date_start of this NewTask.  # noqa: E501
        :rtype: datetime
        """
        return self._date_start

    @date_start.setter
    def date_start(self, date_start):
        """Sets the date_start of this NewTask.


        :param date_start: The date_start of this NewTask.  # noqa: E501
        :type: datetime
        """

        self._date_start = date_start

    @property
    def date_start_utc(self):
        """Gets the date_start_utc of this NewTask.  # noqa: E501


        :return: The date_start_utc of this NewTask.  # noqa: E501
        :rtype: datetime
        """
        return self._date_start_utc

    @date_start_utc.setter
    def date_start_utc(self, date_start_utc):
        """Sets the date_start_utc of this NewTask.


        :param date_start_utc: The date_start_utc of this NewTask.  # noqa: E501
        :type: datetime
        """

        self._date_start_utc = date_start_utc

    @property
    def date_due(self):
        """Gets the date_due of this NewTask.  # noqa: E501


        :return: The date_due of this NewTask.  # noqa: E501
        :rtype: datetime
        """
        return self._date_due

    @date_due.setter
    def date_due(self, date_due):
        """Sets the date_due of this NewTask.


        :param date_due: The date_due of this NewTask.  # noqa: E501
        :type: datetime
        """

        self._date_due = date_due

    @property
    def date_due_utc(self):
        """Gets the date_due_utc of this NewTask.  # noqa: E501


        :return: The date_due_utc of this NewTask.  # noqa: E501
        :rtype: datetime
        """
        return self._date_due_utc

    @date_due_utc.setter
    def date_due_utc(self, date_due_utc):
        """Sets the date_due_utc of this NewTask.


        :param date_due_utc: The date_due_utc of this NewTask.  # noqa: E501
        :type: datetime
        """

        self._date_due_utc = date_due_utc

    @property
    def estimated_effort(self):
        """Gets the estimated_effort of this NewTask.  # noqa: E501

        Decimal hours  # noqa: E501

        :return: The estimated_effort of this NewTask.  # noqa: E501
        :rtype: float
        """
        return self._estimated_effort

    @estimated_effort.setter
    def estimated_effort(self, estimated_effort):
        """Sets the estimated_effort of this NewTask.

        Decimal hours  # noqa: E501

        :param estimated_effort: The estimated_effort of this NewTask.  # noqa: E501
        :type: float
        """

        self._estimated_effort = estimated_effort

    @property
    def tags(self):
        """Gets the tags of this NewTask.  # noqa: E501

        Collection of tags specifying Name and Color (Hex)  # noqa: E501

        :return: The tags of this NewTask.  # noqa: E501
        :rtype: list[NewTag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this NewTask.

        Collection of tags specifying Name and Color (Hex)  # noqa: E501

        :param tags: The tags of this NewTask.  # noqa: E501
        :type: list[NewTag]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
