# coding: utf-8

"""
    Avaza API Documentation

    Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization endpoint: https://any.avaza.com/oauth2/authorize  <br/>OAuth2 Token endpoint: https://any.avaza.com/oauth2/token<br/>Base URL for subsequent API Requests: https://api.avaza.com/ <br/><br/>Blogpost about authenticating with Avaza's API:  https://www.avaza.com/avaza-api-oauth2-authentication/ <br/>Blogpost on using Avaza's webhooks: https://www.avaza.com/avaza-api-webhook-notifications/<br/>The OAuth flow currently issues Access Tokens that last 1 day, and Refresh tokens that last 180 days<br/>The Api respects the security Roles assigned to the authenticating Avaza user and filters the data return appropriately. <br/><br><strong>Support</strong><br/>For API Support, and to request access please contact Avaza Support Team via our support chat. <br/><br/><strong>User Contributed Libraries:</strong><br/>Graciously contributed by 3rd party users like you. <br/>Note these are not tested or endorsesd by Avaza. We encourage you to review before use, and use at own risk.<br/> <ul><li> - <a target='blank' href='https://packagist.org/packages/debiprasad/oauth2-avaza'>PHP OAuth Client Package for Azava API (by Debiprasad Sahoo)</a></li></ul>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from avazacli.models.payment_allocation import PaymentAllocation  # noqa: F401,E501


class Payment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaction_id': 'int',
        'account_idfk': 'int',
        'transaction_prefix': 'str',
        'payment_number': 'str',
        'transaction_reference': 'str',
        'customer_idfk': 'int',
        'date_issued': 'datetime',
        'transaction_status_code': 'str',
        'payment_provider_code': 'str',
        'exchange_rate': 'float',
        'balance': 'float',
        'currency_code': 'str',
        'total_amount': 'float',
        'notes': 'str',
        'date_created': 'datetime',
        'date_updated': 'datetime',
        'payment_allocations': 'list[PaymentAllocation]'
    }

    attribute_map = {
        'transaction_id': 'TransactionID',
        'account_idfk': 'AccountIDFK',
        'transaction_prefix': 'TransactionPrefix',
        'payment_number': 'PaymentNumber',
        'transaction_reference': 'TransactionReference',
        'customer_idfk': 'CustomerIDFK',
        'date_issued': 'DateIssued',
        'transaction_status_code': 'TransactionStatusCode',
        'payment_provider_code': 'PaymentProviderCode',
        'exchange_rate': 'ExchangeRate',
        'balance': 'Balance',
        'currency_code': 'CurrencyCode',
        'total_amount': 'TotalAmount',
        'notes': 'Notes',
        'date_created': 'DateCreated',
        'date_updated': 'DateUpdated',
        'payment_allocations': 'PaymentAllocations'
    }

    def __init__(self, transaction_id=None, account_idfk=None, transaction_prefix=None, payment_number=None, transaction_reference=None, customer_idfk=None, date_issued=None, transaction_status_code=None, payment_provider_code=None, exchange_rate=None, balance=None, currency_code=None, total_amount=None, notes=None, date_created=None, date_updated=None, payment_allocations=None):  # noqa: E501
        """Payment - a model defined in Swagger"""  # noqa: E501

        self._transaction_id = None
        self._account_idfk = None
        self._transaction_prefix = None
        self._payment_number = None
        self._transaction_reference = None
        self._customer_idfk = None
        self._date_issued = None
        self._transaction_status_code = None
        self._payment_provider_code = None
        self._exchange_rate = None
        self._balance = None
        self._currency_code = None
        self._total_amount = None
        self._notes = None
        self._date_created = None
        self._date_updated = None
        self._payment_allocations = None
        self.discriminator = None

        if transaction_id is not None:
            self.transaction_id = transaction_id
        if account_idfk is not None:
            self.account_idfk = account_idfk
        if transaction_prefix is not None:
            self.transaction_prefix = transaction_prefix
        if payment_number is not None:
            self.payment_number = payment_number
        if transaction_reference is not None:
            self.transaction_reference = transaction_reference
        if customer_idfk is not None:
            self.customer_idfk = customer_idfk
        if date_issued is not None:
            self.date_issued = date_issued
        if transaction_status_code is not None:
            self.transaction_status_code = transaction_status_code
        if payment_provider_code is not None:
            self.payment_provider_code = payment_provider_code
        if exchange_rate is not None:
            self.exchange_rate = exchange_rate
        if balance is not None:
            self.balance = balance
        if currency_code is not None:
            self.currency_code = currency_code
        if total_amount is not None:
            self.total_amount = total_amount
        if notes is not None:
            self.notes = notes
        if date_created is not None:
            self.date_created = date_created
        if date_updated is not None:
            self.date_updated = date_updated
        if payment_allocations is not None:
            self.payment_allocations = payment_allocations

    @property
    def transaction_id(self):
        """Gets the transaction_id of this Payment.  # noqa: E501


        :return: The transaction_id of this Payment.  # noqa: E501
        :rtype: int
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this Payment.


        :param transaction_id: The transaction_id of this Payment.  # noqa: E501
        :type: int
        """

        self._transaction_id = transaction_id

    @property
    def account_idfk(self):
        """Gets the account_idfk of this Payment.  # noqa: E501


        :return: The account_idfk of this Payment.  # noqa: E501
        :rtype: int
        """
        return self._account_idfk

    @account_idfk.setter
    def account_idfk(self, account_idfk):
        """Sets the account_idfk of this Payment.


        :param account_idfk: The account_idfk of this Payment.  # noqa: E501
        :type: int
        """

        self._account_idfk = account_idfk

    @property
    def transaction_prefix(self):
        """Gets the transaction_prefix of this Payment.  # noqa: E501


        :return: The transaction_prefix of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._transaction_prefix

    @transaction_prefix.setter
    def transaction_prefix(self, transaction_prefix):
        """Sets the transaction_prefix of this Payment.


        :param transaction_prefix: The transaction_prefix of this Payment.  # noqa: E501
        :type: str
        """

        self._transaction_prefix = transaction_prefix

    @property
    def payment_number(self):
        """Gets the payment_number of this Payment.  # noqa: E501


        :return: The payment_number of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._payment_number

    @payment_number.setter
    def payment_number(self, payment_number):
        """Sets the payment_number of this Payment.


        :param payment_number: The payment_number of this Payment.  # noqa: E501
        :type: str
        """

        self._payment_number = payment_number

    @property
    def transaction_reference(self):
        """Gets the transaction_reference of this Payment.  # noqa: E501


        :return: The transaction_reference of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._transaction_reference

    @transaction_reference.setter
    def transaction_reference(self, transaction_reference):
        """Sets the transaction_reference of this Payment.


        :param transaction_reference: The transaction_reference of this Payment.  # noqa: E501
        :type: str
        """

        self._transaction_reference = transaction_reference

    @property
    def customer_idfk(self):
        """Gets the customer_idfk of this Payment.  # noqa: E501


        :return: The customer_idfk of this Payment.  # noqa: E501
        :rtype: int
        """
        return self._customer_idfk

    @customer_idfk.setter
    def customer_idfk(self, customer_idfk):
        """Sets the customer_idfk of this Payment.


        :param customer_idfk: The customer_idfk of this Payment.  # noqa: E501
        :type: int
        """

        self._customer_idfk = customer_idfk

    @property
    def date_issued(self):
        """Gets the date_issued of this Payment.  # noqa: E501


        :return: The date_issued of this Payment.  # noqa: E501
        :rtype: datetime
        """
        return self._date_issued

    @date_issued.setter
    def date_issued(self, date_issued):
        """Sets the date_issued of this Payment.


        :param date_issued: The date_issued of this Payment.  # noqa: E501
        :type: datetime
        """

        self._date_issued = date_issued

    @property
    def transaction_status_code(self):
        """Gets the transaction_status_code of this Payment.  # noqa: E501


        :return: The transaction_status_code of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._transaction_status_code

    @transaction_status_code.setter
    def transaction_status_code(self, transaction_status_code):
        """Sets the transaction_status_code of this Payment.


        :param transaction_status_code: The transaction_status_code of this Payment.  # noqa: E501
        :type: str
        """

        self._transaction_status_code = transaction_status_code

    @property
    def payment_provider_code(self):
        """Gets the payment_provider_code of this Payment.  # noqa: E501


        :return: The payment_provider_code of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._payment_provider_code

    @payment_provider_code.setter
    def payment_provider_code(self, payment_provider_code):
        """Sets the payment_provider_code of this Payment.


        :param payment_provider_code: The payment_provider_code of this Payment.  # noqa: E501
        :type: str
        """

        self._payment_provider_code = payment_provider_code

    @property
    def exchange_rate(self):
        """Gets the exchange_rate of this Payment.  # noqa: E501


        :return: The exchange_rate of this Payment.  # noqa: E501
        :rtype: float
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate):
        """Sets the exchange_rate of this Payment.


        :param exchange_rate: The exchange_rate of this Payment.  # noqa: E501
        :type: float
        """

        self._exchange_rate = exchange_rate

    @property
    def balance(self):
        """Gets the balance of this Payment.  # noqa: E501


        :return: The balance of this Payment.  # noqa: E501
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """Sets the balance of this Payment.


        :param balance: The balance of this Payment.  # noqa: E501
        :type: float
        """

        self._balance = balance

    @property
    def currency_code(self):
        """Gets the currency_code of this Payment.  # noqa: E501


        :return: The currency_code of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this Payment.


        :param currency_code: The currency_code of this Payment.  # noqa: E501
        :type: str
        """

        self._currency_code = currency_code

    @property
    def total_amount(self):
        """Gets the total_amount of this Payment.  # noqa: E501


        :return: The total_amount of this Payment.  # noqa: E501
        :rtype: float
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """Sets the total_amount of this Payment.


        :param total_amount: The total_amount of this Payment.  # noqa: E501
        :type: float
        """

        self._total_amount = total_amount

    @property
    def notes(self):
        """Gets the notes of this Payment.  # noqa: E501


        :return: The notes of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this Payment.


        :param notes: The notes of this Payment.  # noqa: E501
        :type: str
        """

        self._notes = notes

    @property
    def date_created(self):
        """Gets the date_created of this Payment.  # noqa: E501


        :return: The date_created of this Payment.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this Payment.


        :param date_created: The date_created of this Payment.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_updated(self):
        """Gets the date_updated of this Payment.  # noqa: E501


        :return: The date_updated of this Payment.  # noqa: E501
        :rtype: datetime
        """
        return self._date_updated

    @date_updated.setter
    def date_updated(self, date_updated):
        """Sets the date_updated of this Payment.


        :param date_updated: The date_updated of this Payment.  # noqa: E501
        :type: datetime
        """

        self._date_updated = date_updated

    @property
    def payment_allocations(self):
        """Gets the payment_allocations of this Payment.  # noqa: E501


        :return: The payment_allocations of this Payment.  # noqa: E501
        :rtype: list[PaymentAllocation]
        """
        return self._payment_allocations

    @payment_allocations.setter
    def payment_allocations(self, payment_allocations):
        """Sets the payment_allocations of this Payment.


        :param payment_allocations: The payment_allocations of this Payment.  # noqa: E501
        :type: list[PaymentAllocation]
        """

        self._payment_allocations = payment_allocations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Payment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
