# coding: utf-8

"""
    Avaza API Documentation

    Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization endpoint: https://any.avaza.com/oauth2/authorize  <br/>OAuth2 Token endpoint: https://any.avaza.com/oauth2/token<br/>Base URL for subsequent API Requests: https://api.avaza.com/ <br/><br/>Blogpost about authenticating with Avaza's API:  https://www.avaza.com/avaza-api-oauth2-authentication/ <br/>Blogpost on using Avaza's webhooks: https://www.avaza.com/avaza-api-webhook-notifications/<br/>The OAuth flow currently issues Access Tokens that last 1 day, and Refresh tokens that last 180 days<br/>The Api respects the security Roles assigned to the authenticating Avaza user and filters the data return appropriately. <br/><br><strong>Support</strong><br/>For API Support, and to request access please contact Avaza Support Team via our support chat. <br/><br/><strong>User Contributed Libraries:</strong><br/>Graciously contributed by 3rd party users like you. <br/>Note these are not tested or endorsesd by Avaza. We encourage you to review before use, and use at own risk.<br/> <ul><li> - <a target='blank' href='https://packagist.org/packages/debiprasad/oauth2-avaza'>PHP OAuth Client Package for Azava API (by Debiprasad Sahoo)</a></li></ul>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from avazacli.models.role_details import RoleDetails  # noqa: F401,E501
from avazacli.models.user_tag_details import UserTagDetails  # noqa: F401,E501


class UserDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'int',
        'account_idfk': 'int',
        'email': 'str',
        'firstname': 'str',
        'lastname': 'str',
        'position_title': 'str',
        'phone': 'str',
        'mobile': 'str',
        'time_zone': 'str',
        'is_team_member': 'bool',
        'company_idfk': 'int',
        'company_name': 'str',
        'default_billable_rate': 'float',
        'default_cost_rate': 'float',
        'monday_available_hours': 'float',
        'tuesday_available_hours': 'float',
        'wednesday_available_hours': 'float',
        'thursday_available_hours': 'float',
        'friday_available_hours': 'float',
        'saturday_available_hours': 'float',
        'sunday_available_hours': 'float',
        'roles': 'list[RoleDetails]',
        'tags': 'list[UserTagDetails]'
    }

    attribute_map = {
        'user_id': 'UserID',
        'account_idfk': 'AccountIDFK',
        'email': 'Email',
        'firstname': 'Firstname',
        'lastname': 'Lastname',
        'position_title': 'PositionTitle',
        'phone': 'Phone',
        'mobile': 'Mobile',
        'time_zone': 'TimeZone',
        'is_team_member': 'isTeamMember',
        'company_idfk': 'CompanyIDFK',
        'company_name': 'CompanyName',
        'default_billable_rate': 'DefaultBillableRate',
        'default_cost_rate': 'DefaultCostRate',
        'monday_available_hours': 'MondayAvailableHours',
        'tuesday_available_hours': 'TuesdayAvailableHours',
        'wednesday_available_hours': 'WednesdayAvailableHours',
        'thursday_available_hours': 'ThursdayAvailableHours',
        'friday_available_hours': 'FridayAvailableHours',
        'saturday_available_hours': 'SaturdayAvailableHours',
        'sunday_available_hours': 'SundayAvailableHours',
        'roles': 'Roles',
        'tags': 'Tags'
    }

    def __init__(self, user_id=None, account_idfk=None, email=None, firstname=None, lastname=None, position_title=None, phone=None, mobile=None, time_zone=None, is_team_member=None, company_idfk=None, company_name=None, default_billable_rate=None, default_cost_rate=None, monday_available_hours=None, tuesday_available_hours=None, wednesday_available_hours=None, thursday_available_hours=None, friday_available_hours=None, saturday_available_hours=None, sunday_available_hours=None, roles=None, tags=None):  # noqa: E501
        """UserDetails - a model defined in Swagger"""  # noqa: E501

        self._user_id = None
        self._account_idfk = None
        self._email = None
        self._firstname = None
        self._lastname = None
        self._position_title = None
        self._phone = None
        self._mobile = None
        self._time_zone = None
        self._is_team_member = None
        self._company_idfk = None
        self._company_name = None
        self._default_billable_rate = None
        self._default_cost_rate = None
        self._monday_available_hours = None
        self._tuesday_available_hours = None
        self._wednesday_available_hours = None
        self._thursday_available_hours = None
        self._friday_available_hours = None
        self._saturday_available_hours = None
        self._sunday_available_hours = None
        self._roles = None
        self._tags = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if account_idfk is not None:
            self.account_idfk = account_idfk
        if email is not None:
            self.email = email
        if firstname is not None:
            self.firstname = firstname
        if lastname is not None:
            self.lastname = lastname
        if position_title is not None:
            self.position_title = position_title
        if phone is not None:
            self.phone = phone
        if mobile is not None:
            self.mobile = mobile
        if time_zone is not None:
            self.time_zone = time_zone
        if is_team_member is not None:
            self.is_team_member = is_team_member
        if company_idfk is not None:
            self.company_idfk = company_idfk
        if company_name is not None:
            self.company_name = company_name
        if default_billable_rate is not None:
            self.default_billable_rate = default_billable_rate
        if default_cost_rate is not None:
            self.default_cost_rate = default_cost_rate
        if monday_available_hours is not None:
            self.monday_available_hours = monday_available_hours
        if tuesday_available_hours is not None:
            self.tuesday_available_hours = tuesday_available_hours
        if wednesday_available_hours is not None:
            self.wednesday_available_hours = wednesday_available_hours
        if thursday_available_hours is not None:
            self.thursday_available_hours = thursday_available_hours
        if friday_available_hours is not None:
            self.friday_available_hours = friday_available_hours
        if saturday_available_hours is not None:
            self.saturday_available_hours = saturday_available_hours
        if sunday_available_hours is not None:
            self.sunday_available_hours = sunday_available_hours
        if roles is not None:
            self.roles = roles
        if tags is not None:
            self.tags = tags

    @property
    def user_id(self):
        """Gets the user_id of this UserDetails.  # noqa: E501


        :return: The user_id of this UserDetails.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserDetails.


        :param user_id: The user_id of this UserDetails.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def account_idfk(self):
        """Gets the account_idfk of this UserDetails.  # noqa: E501


        :return: The account_idfk of this UserDetails.  # noqa: E501
        :rtype: int
        """
        return self._account_idfk

    @account_idfk.setter
    def account_idfk(self, account_idfk):
        """Sets the account_idfk of this UserDetails.


        :param account_idfk: The account_idfk of this UserDetails.  # noqa: E501
        :type: int
        """

        self._account_idfk = account_idfk

    @property
    def email(self):
        """Gets the email of this UserDetails.  # noqa: E501


        :return: The email of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserDetails.


        :param email: The email of this UserDetails.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def firstname(self):
        """Gets the firstname of this UserDetails.  # noqa: E501


        :return: The firstname of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this UserDetails.


        :param firstname: The firstname of this UserDetails.  # noqa: E501
        :type: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """Gets the lastname of this UserDetails.  # noqa: E501


        :return: The lastname of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this UserDetails.


        :param lastname: The lastname of this UserDetails.  # noqa: E501
        :type: str
        """

        self._lastname = lastname

    @property
    def position_title(self):
        """Gets the position_title of this UserDetails.  # noqa: E501


        :return: The position_title of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._position_title

    @position_title.setter
    def position_title(self, position_title):
        """Sets the position_title of this UserDetails.


        :param position_title: The position_title of this UserDetails.  # noqa: E501
        :type: str
        """

        self._position_title = position_title

    @property
    def phone(self):
        """Gets the phone of this UserDetails.  # noqa: E501


        :return: The phone of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this UserDetails.


        :param phone: The phone of this UserDetails.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def mobile(self):
        """Gets the mobile of this UserDetails.  # noqa: E501


        :return: The mobile of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._mobile

    @mobile.setter
    def mobile(self, mobile):
        """Sets the mobile of this UserDetails.


        :param mobile: The mobile of this UserDetails.  # noqa: E501
        :type: str
        """

        self._mobile = mobile

    @property
    def time_zone(self):
        """Gets the time_zone of this UserDetails.  # noqa: E501


        :return: The time_zone of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._time_zone

    @time_zone.setter
    def time_zone(self, time_zone):
        """Sets the time_zone of this UserDetails.


        :param time_zone: The time_zone of this UserDetails.  # noqa: E501
        :type: str
        """

        self._time_zone = time_zone

    @property
    def is_team_member(self):
        """Gets the is_team_member of this UserDetails.  # noqa: E501


        :return: The is_team_member of this UserDetails.  # noqa: E501
        :rtype: bool
        """
        return self._is_team_member

    @is_team_member.setter
    def is_team_member(self, is_team_member):
        """Sets the is_team_member of this UserDetails.


        :param is_team_member: The is_team_member of this UserDetails.  # noqa: E501
        :type: bool
        """

        self._is_team_member = is_team_member

    @property
    def company_idfk(self):
        """Gets the company_idfk of this UserDetails.  # noqa: E501


        :return: The company_idfk of this UserDetails.  # noqa: E501
        :rtype: int
        """
        return self._company_idfk

    @company_idfk.setter
    def company_idfk(self, company_idfk):
        """Sets the company_idfk of this UserDetails.


        :param company_idfk: The company_idfk of this UserDetails.  # noqa: E501
        :type: int
        """

        self._company_idfk = company_idfk

    @property
    def company_name(self):
        """Gets the company_name of this UserDetails.  # noqa: E501


        :return: The company_name of this UserDetails.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this UserDetails.


        :param company_name: The company_name of this UserDetails.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def default_billable_rate(self):
        """Gets the default_billable_rate of this UserDetails.  # noqa: E501


        :return: The default_billable_rate of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._default_billable_rate

    @default_billable_rate.setter
    def default_billable_rate(self, default_billable_rate):
        """Sets the default_billable_rate of this UserDetails.


        :param default_billable_rate: The default_billable_rate of this UserDetails.  # noqa: E501
        :type: float
        """

        self._default_billable_rate = default_billable_rate

    @property
    def default_cost_rate(self):
        """Gets the default_cost_rate of this UserDetails.  # noqa: E501


        :return: The default_cost_rate of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._default_cost_rate

    @default_cost_rate.setter
    def default_cost_rate(self, default_cost_rate):
        """Sets the default_cost_rate of this UserDetails.


        :param default_cost_rate: The default_cost_rate of this UserDetails.  # noqa: E501
        :type: float
        """

        self._default_cost_rate = default_cost_rate

    @property
    def monday_available_hours(self):
        """Gets the monday_available_hours of this UserDetails.  # noqa: E501


        :return: The monday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._monday_available_hours

    @monday_available_hours.setter
    def monday_available_hours(self, monday_available_hours):
        """Sets the monday_available_hours of this UserDetails.


        :param monday_available_hours: The monday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._monday_available_hours = monday_available_hours

    @property
    def tuesday_available_hours(self):
        """Gets the tuesday_available_hours of this UserDetails.  # noqa: E501


        :return: The tuesday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._tuesday_available_hours

    @tuesday_available_hours.setter
    def tuesday_available_hours(self, tuesday_available_hours):
        """Sets the tuesday_available_hours of this UserDetails.


        :param tuesday_available_hours: The tuesday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._tuesday_available_hours = tuesday_available_hours

    @property
    def wednesday_available_hours(self):
        """Gets the wednesday_available_hours of this UserDetails.  # noqa: E501


        :return: The wednesday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._wednesday_available_hours

    @wednesday_available_hours.setter
    def wednesday_available_hours(self, wednesday_available_hours):
        """Sets the wednesday_available_hours of this UserDetails.


        :param wednesday_available_hours: The wednesday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._wednesday_available_hours = wednesday_available_hours

    @property
    def thursday_available_hours(self):
        """Gets the thursday_available_hours of this UserDetails.  # noqa: E501


        :return: The thursday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._thursday_available_hours

    @thursday_available_hours.setter
    def thursday_available_hours(self, thursday_available_hours):
        """Sets the thursday_available_hours of this UserDetails.


        :param thursday_available_hours: The thursday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._thursday_available_hours = thursday_available_hours

    @property
    def friday_available_hours(self):
        """Gets the friday_available_hours of this UserDetails.  # noqa: E501


        :return: The friday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._friday_available_hours

    @friday_available_hours.setter
    def friday_available_hours(self, friday_available_hours):
        """Sets the friday_available_hours of this UserDetails.


        :param friday_available_hours: The friday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._friday_available_hours = friday_available_hours

    @property
    def saturday_available_hours(self):
        """Gets the saturday_available_hours of this UserDetails.  # noqa: E501


        :return: The saturday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._saturday_available_hours

    @saturday_available_hours.setter
    def saturday_available_hours(self, saturday_available_hours):
        """Sets the saturday_available_hours of this UserDetails.


        :param saturday_available_hours: The saturday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._saturday_available_hours = saturday_available_hours

    @property
    def sunday_available_hours(self):
        """Gets the sunday_available_hours of this UserDetails.  # noqa: E501


        :return: The sunday_available_hours of this UserDetails.  # noqa: E501
        :rtype: float
        """
        return self._sunday_available_hours

    @sunday_available_hours.setter
    def sunday_available_hours(self, sunday_available_hours):
        """Sets the sunday_available_hours of this UserDetails.


        :param sunday_available_hours: The sunday_available_hours of this UserDetails.  # noqa: E501
        :type: float
        """

        self._sunday_available_hours = sunday_available_hours

    @property
    def roles(self):
        """Gets the roles of this UserDetails.  # noqa: E501


        :return: The roles of this UserDetails.  # noqa: E501
        :rtype: list[RoleDetails]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this UserDetails.


        :param roles: The roles of this UserDetails.  # noqa: E501
        :type: list[RoleDetails]
        """

        self._roles = roles

    @property
    def tags(self):
        """Gets the tags of this UserDetails.  # noqa: E501


        :return: The tags of this UserDetails.  # noqa: E501
        :rtype: list[UserTagDetails]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this UserDetails.


        :param tags: The tags of this UserDetails.  # noqa: E501
        :type: list[UserTagDetails]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
